### ISSUE TITLE
AdvancedADC.h missing

### ISSUE THREAD

**Issue by mdushkoff** [ryanfobel/dmf_control_board#1]
I've been trying to compile the dmf_control_board code and it keeps complaining that `AdvancedADC.h` does not exist.  I have searched quite a while to find this file and the only thing that comes up is the reference to the code in this library that uses it, which is not quite helpful...  Is there a separate library that I have to download and put into the /Arduino/libraries/ folder that I just can't find, or is it a separate issue entirely?

**Comment by ryanfobel** [comment]
Yes, you can download it here:

http://microfluidics.utoronto.ca/git/arduino___advanced_adc_library.git/snapshot/master

You will need to unzip the contents to your Arduino libraries folder under
a subfolder called "AdvancedADC".

-Ryan

**Comment by mdushkoff** [comment]
Thank you for directing me to this, I didn't notice it was there in the repositories...
Now I'm getting an error with the library after placing it in the Arduino library folder and compiling it for the ATMega 2560:

```
AdvancedADC.h:101:15: error: inlining failed in call to always_inline 'static void ADCClass::stop()': function body not available
static void stop() __attribute__((always_inline));
```

This error repeats for all of the functions that are trying to be called and I even tried to run the benchmark file included with the library with the same results.

I'm using the Arduino 1.6.3 IDE if that makes any difference...

**Comment by ryanfobel** [comment]
I haven't tried compiling with 1.6.3.

Can you try it with 1.0.5-r2?

-Ryan

**Comment by mdushkoff** [comment]
Thanks so much, that worked perfectly when I downgraded to 1.0.5-r2!

**Comment by ryanfobel** [comment]
No problem.
